export const categories = [
    {
        id: "01",
        category:"BreakFast",
    },  
      {
        id: "02",
        category:"Lunch",
    }, 
        {
        id: "03",
        category:"Dinner",
    }, 
          {
        id: "04",
        category:"Asian",
    }, 
            {
        id: "05",
        category:"Italian",
    }, 
              {
        id: "06",
        category:"Dessert",
    }, 
                {
        id: "07",
        category:"Vegetarian",
    }, 
                  {
        id: "08",
        category:"SeaFood",
  }, 
];

export const recipeList = [
  {
    id: "01",
    name: "Tuna Tartare",
    image: require("../assets/images/food1.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "420 cal",
    color: "black",
    description:
      "Tuna is a versatile fish commonly used in various dishes, often appreciated for its mild flavor and flaky texture.",
    steps: [
      "Drain the canned tuna and flake it into a bowl using a fork.",
      "Add desired seasonings such as salt, pepper, lemon juice, mayonnaise, chopped onions, celery, or herbs.",
      "Mix the tuna and seasonings until well combined.",
      "Spread the tuna mixture onto slices of bread or crackers for a sandwich or snack, or use it as a topping for salads or pasta.",
      "Serve and enjoy your tuna creation!",
    ],
  },
  {
    id: "02",
    name: "hotdog",
    image: require("../assets/images/welcome.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Easy",
    calories: "300 cal",
    color: "pink",
    description:
      "A hotdog is a type of sausage served in a sliced bun, often garnished with condiments like mustard, ketchup, onions, relish, or sauerkraut.",
    steps: [
      "Preheat a grill or grill pan over medium-high heat.",
      "Grill the hotdogs for 5-7 minutes, turning occasionally, until they are heated through and have grill marks.",
      "While grilling, lightly toast the buns on the grill for about 1-2 minutes.",
      "Place the grilled hotdogs into the toasted buns.",
      "Add desired condiments such as mustard, ketchup, onions, relish, or sauerkraut, and serve immediately.",
    ],
  },
  {
    id: "03",
    name: "Tuna Tartare",
    image: require("../assets/images/food1.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Hard",
    calories: "420 cal",
    color: "blue",
    description:
      "A hotdog is a type of sausage served in a sliced bun, often garnished with condiments like mustard, ketchup, onions, relish, or sauerkraut.",
    steps: [
      "Preheat a grill or grill pan over medium-high heat.",
      "Grill the hotdogs for 5-7 minutes, turning occasionally, until they are heated through and have grill marks.",
      "While grilling, lightly toast the buns on the grill for about 1-2 minutes.",
      "Place the grilled hotdogs into the toasted buns.",
      "Add desired condiments such as mustard, ketchup, onions, relish, or sauerkraut, and serve immediately.",
    ],
  },
  {
    id: "04",
    name: "Tuna Tartare",
    image: require("../assets/images/welcome.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Hard",
    calories: "250 cal",
    color: "yellow",
    description:
      "A hotdog is a type of sausage served in a sliced bun, often garnished with condiments like mustard, ketchup, onions, relish, or sauerkraut.",
    steps: [
      "Preheat a grill or grill pan over medium-high heat.",
      "Grill the hotdogs for 5-7 minutes, turning occasionally, until they are heated through and have grill marks.",
      "While grilling, lightly toast the buns on the grill for about 1-2 minutes.",
      "Place the grilled hotdogs into the toasted buns.",
      "Add desired condiments such as mustard, ketchup, onions, relish, or sauerkraut, and serve immediately.",
    ],
  },
  {
    id: "05",
    name: "Lasagna",
    image: require("../assets/images/food1.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Easy",
    calories: "1000 cal",
    color: "#f39c12",
    description:
      "Lasagna is a classic Italian dish consisting of layers of wide flat pasta, rich meat sauce, creamy béchamel, and melted cheese baked to perfection.",
    steps: [
      "Preheat the oven to 375°F (190°C).",
      "Prepare the meat sauce by browning ground beef with onions, garlic, tomato sauce, and Italian seasoning.",
      "In a separate saucepan, prepare the béchamel sauce by melting butter, whisking in flour, and slowly adding milk until thickened.",
      "In a baking dish, layer the lasagna noodles, meat sauce, béchamel, and shredded cheese, repeating until all ingredients are used up, with the top layer being cheese.",
      "Cover the baking dish with foil and bake for 25-30 minutes, then remove the foil and bake for an additional 10-15 minutes until the cheese is bubbly and golden brown.",
    ],
  },
  {
    id: "06",
    name: "Tuna Tartare",
    image: require("../assets/images/food1.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "220 cal",
    color: "gray",
    description:
      "Lasagna is a classic Italian dish consisting of layers of wide flat pasta, rich meat sauce, creamy béchamel, and melted cheese baked to perfection.",
    steps: [
      "Preheat the oven to 375°F (190°C).",
      "Prepare the meat sauce by browning ground beef with onions, garlic, tomato sauce, and Italian seasoning.",
      "In a separate saucepan, prepare the béchamel sauce by melting butter, whisking in flour, and slowly adding milk until thickened.",
      "In a baking dish, layer the lasagna noodles, meat sauce, béchamel, and shredded cheese, repeating until all ingredients are used up, with the top layer being cheese.",
      "Cover the baking dish with foil and bake for 25-30 minutes, then remove the foil and bake for an additional 10-15 minutes until the cheese is bubbly and golden brown.",
    ],
  },
  {
    id: "07",
    name: "Chicken",
    image: require("../assets/images/welcome.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "100 cal",
    color: "#f39c12",
    description:
      "Chicken is a popular protein choice known for its versatility and mild flavor, often used in a variety of cuisines and dishes.",
    steps: [
      "Preheat the oven to 375°F (190°C).",
      "Season chicken breasts with salt, pepper, and any desired herbs or spices.",
      "Heat oil in an oven-safe skillet over medium-high heat.",
      "Sear the seasoned chicken breasts in the skillet until golden brown on both sides, about 3-4 minutes per side.",
      "Transfer the skillet to the preheated oven and bake for 20-25 minutes, or until the chicken is cooked through and reaches an internal temperature of 165°F (75°C).",
      "Remove the skillet from the oven, let the chicken rest for a few minutes, then slice and serve.",
    ],
  },
  {
    id: "08",
    name: "Tuna Tartare",
    image: require("../assets/images/food2.png"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Easy",
    calories: "40 cal",
    color: "purple",
    description:
      "Lasagna is a classic Italian dish consisting of layers of wide flat pasta, rich meat sauce, creamy béchamel, and melted cheese baked to perfection.",
    steps: [
      "Preheat the oven to 375°F (190°C).",
      "Prepare the meat sauce by browning ground beef with onions, garlic, tomato sauce, and Italian seasoning.",
      "In a separate saucepan, prepare the béchamel sauce by melting butter, whisking in flour, and slowly adding milk until thickened.",
      "In a baking dish, layer the lasagna noodles, meat sauce, béchamel, and shredded cheese, repeating until all ingredients are used up, with the top layer being cheese.",
      "Cover the baking dish with foil and bake for 25-30 minutes, then remove the foil and bake for an additional 10-15 minutes until the cheese is bubbly and golden brown.",
    ],
  },
];